/*DROP TABLE JOB;

CREATE TABLE JOB (
  JOB_ID number default NULL,
  COMP_ID varchar2(50) default NULL,
  TYPE varchar2(255) default NULL,
  PAY_RATE varchar2(100) default NULL,
  PAY_TYPE varchar2(255) default NULL
);
*/
DELETE FROM JOB;

INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (1,5,'PART-TIME','$47.67','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (2,7,'PART-TIME','$22.81','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (3,1,'PART-TIME','$53.03','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (4,2,'PART-TIME','$27137.03','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (5,8,'PART-TIME','$19458.96','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (6,9,'PART-TIME','$49.90','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (7,3,'FULL-TIME','$70944.81','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (8,10,'FULL-TIME','$51.69','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (9,9,'PART-TIME','$11954.93','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (10,1,'PART-TIME','$16.94','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (11,5,'PART-TIME','$26.51','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (12,10,'FULL-TIME','$20.87','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (13,6,'FULL-TIME','$84.18','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (14,3,'PART-TIME','$13.31','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (15,1,'FULL-TIME','$88778.21','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (16,6,'PART-TIME','$26807.98','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (17,2,'PART-TIME','$42.31','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (18,8,'PART-TIME','$53.49','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (19,8,'FULL-TIME','$40931.14','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (20,6,'FULL-TIME','$83115.37','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (21,1,'PART-TIME','$91.72','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (22,4,'PART-TIME','$18.35','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (23,9,'FULL-TIME','$25.56','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (24,2,'PART-TIME','$57.30','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (25,8,'FULL-TIME','$66724.45','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (26,5,'PART-TIME','$18651.82','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (27,10,'FULL-TIME','$31.89','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (28,4,'PART-TIME','$40.15','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (29,9,'PART-TIME','$22.85','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (30,8,'FULL-TIME','$21.91','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (31,5,'PART-TIME','$43536.69','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (32,8,'PART-TIME','$94.33','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (33,6,'PART-TIME','$77.46','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (34,7,'FULL-TIME','$86078.13','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (35,8,'FULL-TIME','$72649.29','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (36,2,'FULL-TIME','$41.86','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (37,5,'FULL-TIME','$48.50','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (38,7,'PART-TIME','$14.09','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (39,5,'PART-TIME','$38.08','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (40,1,'PART-TIME','$80253.23','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (41,6,'PART-TIME','$29204.22','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (42,4,'PART-TIME','$30412.88','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (43,6,'FULL-TIME','$72245.72','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (44,3,'PART-TIME','$58.09','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (45,3,'FULL-TIME','$22402.05','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (46,9,'PART-TIME','$37951.45','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (47,1,'PART-TIME','$58.92','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (48,10,'PART-TIME','$33882.62','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (49,6,'FULL-TIME','$45568.39','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (50,5,'PART-TIME','$13.07','WAGE');

/*
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (51,8,'PART-TIME','$30731.97','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (52,3,'FULL-TIME','$42227.48','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (53,6,'PART-TIME','$12605.18','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (54,5,'PART-TIME','$44760.59','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (55,1,'PART-TIME','$71898.79','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (56,6,'PART-TIME','$36192.54','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (57,5,'PART-TIME','$33564.47','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (58,4,'PART-TIME','$85253.64','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (59,8,'PART-TIME','$73377.92','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (60,9,'PART-TIME','$10383.15','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (61,2,'PART-TIME','$13012.81','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (62,8,'PART-TIME','$45151.53','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (63,2,'FULL-TIME','$70469.03','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (64,4,'PART-TIME','$23861.42','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (65,7,'PART-TIME','$42879.14','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (66,9,'PART-TIME','$90634.33','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (67,10,'FULL-TIME','$43109.97','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (68,4,'FULL-TIME','$80416.06','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (69,7,'FULL-TIME','$81618.42','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (70,6,'FULL-TIME','$62689.93','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (71,6,'FULL-TIME','$24822.04','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (72,2,'FULL-TIME','$52268.50','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (73,7,'FULL-TIME','$29675.93','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (74,4,'FULL-TIME','$30431.93','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (75,4,'FULL-TIME','$30658.73','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (76,1,'PART-TIME','$18520.84','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (77,6,'FULL-TIME','$26698.30','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (78,4,'FULL-TIME','$78353.79','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (79,7,'FULL-TIME','$80108.93','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (80,7,'PART-TIME','$21843.71','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (81,6,'FULL-TIME','$84011.87','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (82,1,'FULL-TIME','$39305.79','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (83,10,'PART-TIME','$33405.88','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (84,3,'FULL-TIME','$57871.69','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (85,7,'PART-TIME','$68744.71','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (86,6,'PART-TIME','$37423.06','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (87,5,'PART-TIME','$75449.60','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (88,7,'FULL-TIME','$40986.19','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (89,1,'PART-TIME','$27886.11','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (90,3,'FULL-TIME','$09268.33','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (91,2,'PART-TIME','$03567.29','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (92,1,'FULL-TIME','$27246.99','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (93,1,'PART-TIME','$86589.32','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (94,1,'PART-TIME','$30080.92','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (95,6,'PART-TIME','$80810.48','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (96,2,'PART-TIME','$36011.69','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (97,5,'FULL-TIME','$48635.52','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (98,5,'FULL-TIME','$17042.38','SALARY');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (99,6,'PART-TIME','$91551.99','WAGE');
INSERT INTO JOB (JOB_ID,COMP_ID,TYPE,PAY_RATE,PAY_TYPE) VALUES (100,1,'FULL-TIME','$52217.34','WAGE');
*/